// <auto-generated />
using System;
using ConsoleApp30.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp30.Migrations
{
    [DbContext(typeof(carDbContext))]
    [Migration("20260129101104_UpdateCarTable")]
    partial class UpdateCarTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleApp30.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Available");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)")
                        .HasColumnName("VIN");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("CarId")
                        .HasName("PK__Cars__68A0342EE6668455");

                    b.HasIndex("ModelId");

                    b.HasIndex(new[] { "Vin" }, "UQ__Cars__C5DF234C72CED089")
                        .IsUnique();

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("ConsoleApp30.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CustomerId")
                        .HasName("PK__Customer__A4AE64D82A136FBB");

                    b.HasIndex(new[] { "Phone" }, "UQ__Customer__5C7E359E5F5409C0")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ConsoleApp30.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmployeeId")
                        .HasName("PK__Employee__7AD04F11E1D111A2");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ConsoleApp30.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManufacturerId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ManufacturerId")
                        .HasName("PK__Manufact__357E5CC148A8E468");

                    b.HasIndex(new[] { "Name" }, "UQ__Manufact__737584F6D6A35E25")
                        .IsUnique();

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("ConsoleApp30.Models.Model", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ModelId")
                        .HasName("PK__Models__E8D7A12C82F5F064");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("ConsoleApp30.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A38D268F381");

                    b.HasIndex("SaleId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ConsoleApp30.Models.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("SaleDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("SaleId")
                        .HasName("PK__Sales__1EE3C3FF804A0D06");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex(new[] { "CarId" }, "UQ__Sales__68A0342F348D8D5A")
                        .IsUnique();

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("ConsoleApp30.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("ServiceId")
                        .HasName("PK__Services__C51BB00A29CD0242");

                    b.HasIndex(new[] { "Name" }, "UQ__Services__737584F6475642E3")
                        .IsUnique();

                    b.ToTable("Services");
                });

            modelBuilder.Entity("ConsoleApp30.Models.TestDrife", b =>
                {
                    b.Property<int>("TestDriveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestDriveId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("TestDriveDate")
                        .HasColumnType("date");

                    b.HasKey("TestDriveId")
                        .HasName("PK__TestDriv__BF98EF52C7F7FAD4");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.ToTable("TestDrives");
                });

            modelBuilder.Entity("SaleService", b =>
                {
                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("SaleId", "ServiceId")
                        .HasName("PK__SaleServ__A2B278FF6A41827E");

                    b.HasIndex("ServiceId");

                    b.ToTable("SaleServices", (string)null);
                });

            modelBuilder.Entity("ConsoleApp30.Models.Car", b =>
                {
                    b.HasOne("ConsoleApp30.Models.Model", "Model")
                        .WithMany("Cars")
                        .HasForeignKey("ModelId")
                        .IsRequired()
                        .HasConstraintName("FK__Cars__ModelId__4222D4EF");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("ConsoleApp30.Models.Model", b =>
                {
                    b.HasOne("ConsoleApp30.Models.Manufacturer", "Manufacturer")
                        .WithMany("Models")
                        .HasForeignKey("ManufacturerId")
                        .IsRequired()
                        .HasConstraintName("FK__Models__Manufact__3A81B327");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("ConsoleApp30.Models.Payment", b =>
                {
                    b.HasOne("ConsoleApp30.Models.Sale", "Sale")
                        .WithMany("Payments")
                        .HasForeignKey("SaleId")
                        .IsRequired()
                        .HasConstraintName("FK__Payments__SaleId__534D60F1");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("ConsoleApp30.Models.Sale", b =>
                {
                    b.HasOne("ConsoleApp30.Models.Car", "Car")
                        .WithOne("Sale")
                        .HasForeignKey("ConsoleApp30.Models.Sale", "CarId")
                        .IsRequired()
                        .HasConstraintName("FK__Sales__CarId__4BAC3F29");

                    b.HasOne("ConsoleApp30.Models.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__Sales__CustomerI__4CA06362");

                    b.HasOne("ConsoleApp30.Models.Employee", "Employee")
                        .WithMany("Sales")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__Sales__EmployeeI__4D94879B");

                    b.Navigation("Car");

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ConsoleApp30.Models.TestDrife", b =>
                {
                    b.HasOne("ConsoleApp30.Models.Car", "Car")
                        .WithMany("TestDrives")
                        .HasForeignKey("CarId")
                        .IsRequired()
                        .HasConstraintName("FK__TestDrive__CarId__5629CD9C");

                    b.HasOne("ConsoleApp30.Models.Customer", "Customer")
                        .WithMany("TestDrives")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__TestDrive__Custo__571DF1D5");

                    b.Navigation("Car");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SaleService", b =>
                {
                    b.HasOne("ConsoleApp30.Models.Sale", null)
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .IsRequired()
                        .HasConstraintName("FK__SaleServi__SaleI__5DCAEF64");

                    b.HasOne("ConsoleApp30.Models.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__SaleServi__Servi__5EBF139D");
                });

            modelBuilder.Entity("ConsoleApp30.Models.Car", b =>
                {
                    b.Navigation("Sale");

                    b.Navigation("TestDrives");
                });

            modelBuilder.Entity("ConsoleApp30.Models.Customer", b =>
                {
                    b.Navigation("Sales");

                    b.Navigation("TestDrives");
                });

            modelBuilder.Entity("ConsoleApp30.Models.Employee", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("ConsoleApp30.Models.Manufacturer", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("ConsoleApp30.Models.Model", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("ConsoleApp30.Models.Sale", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
